import type { PatternExample } from '@/features/patterns/types/patterns';

export { userSessionSingleton } from './singleton';
export { createProfileProxy } from './proxy';
export { createPrototypeUser } from './prototype';
export { createObservable } from './observer';
export { cartModule } from './module';
export { withTimestamp } from './mixin';
export { createMiddlewarePipeline } from './mediatorMiddleware';
export { iconFlyweightFactory } from './flyweight';
export { createNotification } from './factory';

export const javascriptPatterns: PatternExample[] = [
  {
    id: 'singleton',
    name: 'Singleton',
    category: 'javascript',
    summary: 'Share one global instance for application-wide coordination.',
    implementation: 'src/lib/patterns/javascript/singleton.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'proxy',
    name: 'Proxy',
    category: 'javascript',
    summary: 'Intercept reads and writes to another object.',
    implementation: 'src/lib/patterns/javascript/proxy.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'prototype',
    name: 'Prototype',
    category: 'javascript',
    summary: 'Share behavior through a prototype object.',
    implementation: 'src/lib/patterns/javascript/prototype.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'observer',
    name: 'Observer',
    category: 'javascript',
    summary: 'Notify subscribed listeners when an event occurs.',
    implementation: 'src/lib/patterns/javascript/observer.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'module',
    name: 'Module',
    category: 'javascript',
    summary: 'Expose a small API while keeping implementation details private.',
    implementation: 'src/lib/patterns/javascript/module.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'mixin',
    name: 'Mixin',
    category: 'javascript',
    summary: 'Add reusable behavior to objects without inheritance.',
    implementation: 'src/lib/patterns/javascript/mixin.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'mediator-middleware',
    name: 'Mediator/Middleware',
    category: 'javascript',
    summary: 'Route work through a central pipeline instead of coupling callers.',
    implementation: 'src/lib/patterns/javascript/mediatorMiddleware.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'flyweight',
    name: 'Flyweight',
    category: 'javascript',
    summary: 'Reuse existing instances for repeated identical values.',
    implementation: 'src/lib/patterns/javascript/flyweight.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'factory',
    name: 'Factory',
    category: 'javascript',
    summary: 'Create objects through a function that hides construction details.',
    implementation: 'src/lib/patterns/javascript/factory.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'static-import',
    name: 'Static Import',
    category: 'performance',
    summary: 'Import critical code eagerly at module load time.',
    implementation: 'Use regular ES module imports for above-the-fold dependencies.',
    source: 'Patterns.dev',
  },
  {
    id: 'dynamic-import',
    name: 'Dynamic Import',
    category: 'performance',
    summary: 'Load code on demand with import() or next/dynamic.',
    implementation: 'src/lib/patterns/react/rendering.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'import-on-visibility',
    name: 'Import On Visibility',
    category: 'performance',
    summary: 'Defer non-critical resources until a section enters the viewport.',
    implementation: 'src/features/patterns/hooks/useIntersection.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'import-on-interaction',
    name: 'Import On Interaction',
    category: 'performance',
    summary: 'Load optional code after explicit user intent.',
    implementation: 'Wire dynamic import calls inside click, focus, or hover handlers.',
    source: 'Patterns.dev',
  },
  {
    id: 'route-based-splitting',
    name: 'Route Based Splitting',
    category: 'performance',
    summary: 'Use routes as natural JavaScript bundle boundaries.',
    implementation: 'Next.js App Router creates route-level chunks by default.',
    source: 'Patterns.dev',
  },
  {
    id: 'bundle-splitting',
    name: 'Bundle Splitting',
    category: 'performance',
    summary: 'Split application code into smaller reusable chunks.',
    implementation: 'Prefer route boundaries, dynamic imports, and isolated feature modules.',
    source: 'Patterns.dev',
  },
  {
    id: 'prpl',
    name: 'PRPL',
    category: 'performance',
    summary: 'Push or preload critical assets, render quickly, precache, and lazy load the rest.',
    implementation: 'Use Next prefetching, metadata links, route splitting, and lazy components.',
    source: 'Patterns.dev',
  },
  {
    id: 'tree-shaking',
    name: 'Tree Shaking',
    category: 'performance',
    summary: 'Let the bundler remove unused exports.',
    implementation: 'Keep modules side-effect-light and prefer named exports for utilities.',
    source: 'Patterns.dev',
  },
  {
    id: 'preload',
    name: 'Preload',
    category: 'performance',
    summary: 'Tell the browser about critical resources early.',
    implementation: 'Use Next metadata or explicit link rel="preload" for critical assets.',
    source: 'Patterns.dev',
  },
  {
    id: 'prefetch',
    name: 'Prefetch',
    category: 'performance',
    summary: 'Fetch likely future resources before they are requested.',
    implementation: 'Use next/link prefetching for likely navigation paths.',
    source: 'Patterns.dev',
  },
  {
    id: 'third-parties',
    name: 'Optimize Third Parties',
    category: 'performance',
    summary: 'Load external scripts intentionally to protect page responsiveness.',
    implementation: 'Use next/script strategies and avoid blocking critical rendering.',
    source: 'Patterns.dev',
  },
  {
    id: 'list-virtualization',
    name: 'List Virtualization',
    category: 'performance',
    summary: 'Render only visible rows for very large lists.',
    implementation: 'Adopt a virtualization library when lists become large enough to need it.',
    source: 'Patterns.dev',
  },
  {
    id: 'compressing-javascript',
    name: 'Compressing JavaScript',
    category: 'performance',
    summary: 'Reduce transferred JavaScript bytes with compression.',
    implementation: 'Deploy behind compression-enabled hosting such as Vercel or a CDN.',
    source: 'Patterns.dev',
  },
  {
    id: 'view-transitions',
    name: 'Animating View Transitions',
    category: 'performance',
    summary: 'Use the View Transitions API for continuity between UI states.',
    implementation: 'Guard document.startViewTransition before using browser-only transitions.',
    source: 'Patterns.dev',
  },
  {
    id: 'loading-sequence',
    name: 'Optimize Loading Sequence',
    category: 'performance',
    summary: 'Prioritize the resources needed for the first usable screen.',
    implementation: 'Keep the initial route server-rendered and push non-critical work behind lazy boundaries.',
    source: 'Patterns.dev',
  },
];
