import type { PatternExample } from '@/features/patterns/types/patterns';

export const reactPatterns: PatternExample[] = [
  {
    id: 'container-presentational',
    name: 'Container/Presentational',
    category: 'react',
    summary: 'Keep data and orchestration separate from rendering components.',
    implementation: 'src/features/patterns/containers/PatternExplorerContainer.tsx',
    source: 'Patterns.dev',
  },
  {
    id: 'hoc',
    name: 'Higher-Order Component',
    category: 'react',
    summary: 'Wrap a component to add reusable behavior through props.',
    implementation: 'src/lib/patterns/react/withPatternTelemetry.tsx',
    source: 'Patterns.dev',
  },
  {
    id: 'render-props',
    name: 'Render Props',
    category: 'react',
    summary: 'Pass rendering control as a function prop.',
    implementation: 'src/lib/patterns/react/RenderPropData.tsx',
    source: 'Patterns.dev',
  },
  {
    id: 'hooks',
    name: 'Hooks',
    category: 'react',
    summary: 'Reuse stateful behavior with functions.',
    implementation: 'src/features/patterns/hooks/usePatternFilter.ts',
    source: 'Patterns.dev',
  },
  {
    id: 'compound',
    name: 'Compound Components',
    category: 'react',
    summary: 'Compose related components that cooperate through shared context.',
    implementation: 'src/lib/patterns/react/CompoundTabs.tsx',
    source: 'Patterns.dev',
  },
  {
    id: 'client-side-rendering',
    name: 'Client-side Rendering',
    category: 'react',
    summary: 'Render interactive UI in the browser with client components.',
    implementation: 'Use "use client" components for browser-only state and events.',
    source: 'Patterns.dev',
  },
  {
    id: 'server-side-rendering',
    name: 'Server-side Rendering',
    category: 'react',
    summary: 'Generate HTML on the server for each request when data is dynamic.',
    implementation: 'Use server components or dynamic route rendering in Next.js.',
    source: 'Patterns.dev',
  },
  {
    id: 'static-rendering',
    name: 'Static Rendering',
    category: 'react',
    summary: 'Pre-render stable HTML at build time.',
    implementation: 'Next.js statically renders routes by default when possible.',
    source: 'Patterns.dev',
  },
  {
    id: 'incremental-static-generation',
    name: 'Incremental Static Generation',
    category: 'react',
    summary: 'Refresh static content after deployment.',
    implementation: 'Use fetch revalidate or route segment revalidate in Next.js.',
    source: 'Patterns.dev',
  },
  {
    id: 'progressive-hydration',
    name: 'Progressive Hydration',
    category: 'react',
    summary: 'Hydrate less important interactive regions later.',
    implementation: 'Use server components first, then lazy client islands for lower-priority UI.',
    source: 'Patterns.dev',
  },
  {
    id: 'streaming-ssr',
    name: 'Streaming SSR',
    category: 'react',
    summary: 'Stream HTML chunks as the server resolves them.',
    implementation: 'Use Suspense boundaries and loading.tsx files in the App Router.',
    source: 'Patterns.dev',
  },
  {
    id: 'react-server-components',
    name: 'React Server Components',
    category: 'react',
    summary: 'Render components on the server without shipping their JavaScript.',
    implementation: 'Keep route and template components server-side unless interactivity is needed.',
    source: 'Patterns.dev',
  },
  {
    id: 'core-web-vitals',
    name: 'Core Web Vitals Optimization',
    category: 'react',
    summary: 'Use Next.js primitives that protect loading, layout, and responsiveness metrics.',
    implementation: 'Prefer next/image, next/font, next/script, and route-level streaming.',
    source: 'Patterns.dev',
  },
  {
    id: 'react-stack-patterns',
    name: 'React Stack Patterns',
    category: 'react',
    summary: 'Use modern React stack defaults for routing, rendering, state, and data fetching.',
    implementation: 'This boilerplate uses App Router, server/client component boundaries, and Redux Toolkit.',
    source: 'Patterns.dev',
  },
];
